baseurl = "http://technologyMediaLab.github.io"
languageCode = "ja-jp"
title = "Technology Media Lab"
paginate = 6
description = "A demo site for the material-lite theme"
buildDrafts = true
buildFuture = true

[params]
  TwitterUser = "YourTwitterUsername"
  FacebookUser = "YourFacebookUsername"
  GooglePlusUser = "YourGooglePlusUsername"
  copyright = "&copy; a short copyright statement"
  author = "John Doe"
  background = "a relative or absolute URL to a background image"
  bgcolor = "a background color; will be ignored if you use background"
  primary = "indigo"
  accent = "pink"
